### ISSUE TITLE
How to test types without `Eq` or `Eq1` instances?

### ISSUE THREAD

**Issue by sjakobi** [andrewthad/quickcheck-classes#10]
With `checkers` I can do this by writing [`EqProp`](http://hackage.haskell.org/package/checkers-0.4.9.5/docs/Test-QuickCheck-Checkers.html#t:EqProp) instances that may test e.g. functions for equality.

**Comment by andrewthad** [comment]
I haven't thought a lot about the best way to do this. Right now, this library doesn't attempt to support this. One option is just to write orphan `Eq` and `Show` instances for `->` or the newtype wrappers around it.

**Comment by sjakobi** [comment]
Maybe I'm misunderstanding something but I don't see how you'd write an `Eq` instance for a function with infinitely many input values.

To be clear, `checker`'s `EqProp` can use random sampling to to compare functions, but doing that in an `Eq` instance would at least require some pretty dirty hacks.

**Comment by andrewthad** [comment]
Using the `random` package, one could write:

```
instance (Random a, Eq b) => Eq (a -> b) where
  f == g = all (\x -> f x == g x) (take 100 (randoms (mkStdGen 7)))
```

Random sampling with nothing unsafe about it. This does use the same seed every time though, but you could go down the unsafe route by getting the seed from the system clock with `unsafePerformIO`. I can see why having something like `EqProp` would be appealing though. With it, you could actually show the function argument that was found as a counterexample (although you still cannot show the function, which is sort of a bummer).

Ultimately, I think it would be nice to see something like this, but in QuickCheck instead. In this library, I try to avoid introducing new concepts, instead relying on what QuickCheck provides. I think that what you have suggested would be useful but for a much broader audience than just people who want to test typeclass properties. QuickCheck already has `Function` and `CoArbitrary`, so it's started to go down the route of supporting functions already. It would be nice to see this support expanded.

**Comment by chessai** [comment]
I think it's possible to do the following, very very ugly thing:

```haskell
instance (Show a, Arbitrary a, Eq b) => Eq (a -> b) where
  f == g = fromMaybe False $ ok . getResult $ unProp $ unsafePerformIO $ generate $ unProperty $ property (liftA2 eqProp f g)

getResult :: Rose a -> a
getResult (MkRose x _) = x
getResult (IORose x  ) = getResult $ unsafePerformIO x

eqProp :: Eq a => a -> a -> Property
eqProp a a' = property (a == a')
```

**Comment by chessai** [comment]
I think this request is most likely outside the scope of this library, and should be a change made within QuickCheck.

**Comment by andrewthad** [comment]
I'm going to close this. If anyone is able to get these kind of facilities into `QuickCheck`, let me know, and we can consider using them here.
