### ISSUE TITLE
Missing Num laws for abs and signum

### ISSUE THREAD

**Issue by Bodigrim** [andrewthad/quickcheck-classes#110]
`numLaws` actually misses the only law mentioned in [Haskell Report 2010](https://www.haskell.org/onlinereport/haskell2010/haskellch6.html#x13-1390006.4.4):

```haskell
abs x * signum x == x
``` 

I would also test that 
```haskell
abs (abs x) == abs x 
signum (signum x) == signum x 
```

If we have a consensus on this matter, I can prepare a PR shortly.

**Comment by chessai** [comment]
+1

**Comment by andrewthad** [comment]
Ah, what an oversight!  I would accept a PR adding those three laws.

**Comment by Bodigrim** [comment]
Hmm, `Prelude` mistakenly states that [Haskell Report defines no laws for Num](http://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.Num.html#Num).
