### ISSUE TITLE
Storable laws do not respect alignment

### ISSUE THREAD

**Issue by Bodigrim** [andrewthad/quickcheck-classes#120]
https://github.com/andrewthad/quickcheck-classes/blob/2040e0c252f55d983a30ff23375fa89ccbf0495d/quickcheck-classes-base/src/Test/QuickCheck/Classes/Storable.hs#L81-L103

These laws look a bit suspicious: we choose byte offset up to `len` and not up to `len * sizeOf (_ :: a)`. 

* It's probably not quite right to read data from an unaligned pointer. We should respect [`Foreign.Storable.alignment`](http://hackage.haskell.org/package/base-4.14.0.0/docs/Foreign-Storable.html#v:alignment).
* These tests fail for `Double`. Even while `arbitrary :: Gen Double` never generates `NaN`, reading with a random offset from an array of `Double` can result in data interpreted as `NaN`. And `NaN /= NaN`.

**Comment by andrewthad** [comment]
Yeah, that storable test is certainly wrong. I’d take a PR fixing that. As far as Double failing, I don’t think that anything with non reflexive equality can be tested by this library for anything.
