### ISSUE TITLE
issue with FiniteBits

### ISSUE THREAD

**Issue by chessai** [andrewthad/quickcheck-classes#14]
Currently, `bitsClearZero` is this:

```haskell
bitsClearZero :: forall a. (Bits a, Arbitrary a, Show a) => Proxy a -> Property
bitsClearZero _ = myForAllShrink False (const True)
  (\(n :: a) -> ["n = " ++ show n])
  "complement (complement n)"
  (\n -> complement (complement n))
  "n"
  (\n -> n)
```

But this is just checking that double application of complement is idempotent. Compare to `bitsDoubleComplement`:

```haskell
bitsDoubleComplement :: forall a. (Bits a, Arbitrary a, Show a) => Proxy a -> Property
bitsDoubleComplement _ = myForAllShrink False (const True)
  (\(n :: a) -> ["n = " ++ show n])
  "complement (complement n)"
  (\n -> complement (complement n))
  "n"
  (\n -> n)
```

Same thing. I have a feeling that this may be a result of some copy/pasting that may have gone on.
This error would be hard to catch because for any type with a law-abiding instance of Bits would pass bitsDoubleComplement, and therefore bitsClearZero, silently.

I think it should be:

```haskell
-- clearBit zeroBits n == zeroBits
bitsClearZero :: forall a. (Bits a, Arbitrary a, Show a) => Proxy a -> Property
bitsClearZero _ = myForAllShrink False (const True)
  (\(n :: a) -> ["n = " ++ show n])
  "clearBit zeroBits n"
  (\n -> clearBits zeroBits n)
  "zeroBits"
  (\_ -> zeroBits)
```

**Comment by chessai** [comment]
I opened an issue instead of making a direct commit in case I am wrong.

**Comment by andrewthad** [comment]
Yeah, that test is totally wrong.  You can go ahead and just commit that change directly. Thanks for noticing this.
