### ISSUE TITLE
Better display of counterexamples

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/quickcheck-classes#2]
I've modified all the `Monoid` tests and the partial isomorphism test for `IsList` to give useful information back to the user in the event of a failed test. I should do this for the other classes as well. It's just a matter of finding the time to do it.

**Comment by andrewthad** [comment]
I've done this for monoid and bits as well

**Comment by chessai** [comment]
We could do something like hedgehog does, I think that would be cool

**Comment by andrewthad** [comment]
What hedgehog does is really cool.  It’s also pretty complicated (it tries to load and parse your source code at runtime),  and since quickcheck-classes provides property tests (instead of having the users write them),  I’m not sure if that we could benefit from it.  Although, we could certainly use hedgehog’s presentation of error messages as inspiration.

**Comment by chessai** [comment]
1. is this still an issue?
2. if it is, would it be useful to have a `CounterExample` type that contains useful information?

**Comment by chessai** [comment]
For example, in Refined v3.x, `RefineException`s will contain callstack information as well as the value and some other type information

**Comment by andrewthad** [comment]
For anything I've added recently (`Enum` for example), I've been using code that builds a human-readable string of the counterexample. This is also in place for `Monoid`, `Semigroup`, `Bits`, and `IsList` (and maybe others, but I don't remember offhand). Having a `CounterExample` type wouldn't buy us anything over what we have now since we just have to turn it into a string to present it anyway. I think it's best to close this issue and open up issues for particular typeclass tests if the presentation of their counterexamples in problematic.

**Comment by chessai** [comment]
ok
