### ISSUE TITLE
Inconsistency between presentations of Alternative and MonadPlus laws

### ISSUE THREAD

**Issue by RyanGlScott** [andrewthad/quickcheck-classes#25]
Compare the Haddocks' presentation of the `MonadPlus` laws:

![qc-classes-monadplus](https://user-images.githubusercontent.com/2364661/43017985-0bc30544-8c26-11e8-8269-5744a0d056b0.png)

With those for `Alternative`:

![qc-classes-alternative](https://user-images.githubusercontent.com/2364661/43017992-132b3342-8c26-11e8-87d6-abb6429d4c03.png)

Two things stand out to me:

1. The identity law for `Alternative` currently says:

   ```haskell
   empty <|> x ≡ x x <|> empty ≡ x
   ```

   Should that be this instead?

   ```haskell
   empty <|> x ≡ x
   x <|> empty ≡ x
   ```
2. For `MonadPlus`, there are separate left identity and right identity laws, but for `Alternative`, there is a single "identity". Perhaps `Alternative` should also have separate left identity and right identity laws for consistency?

**Comment by andrewthad** [comment]
You are correct. Alternative's identity laws should be broken out into two separate laws.

**Comment by chessai** [comment]
Please see PR #26
