### ISSUE TITLE
ordering laws should test these

### ISSUE THREAD

**Issue by chessai** [andrewthad/quickcheck-classes#4]
For a type A, there is a total ordering on A if, forall (a : A), (b : A), (c : A),

if (a <= b) && (b <= a) then a == b (antisymmetry)
if (a <= b) && (b <= c) then (a <= c) (transitivity)
(a <= b) || (b <= a)  (totality)

**Comment by chessai** [comment]
PR #5 addresses this

**Comment by andrewthad** [comment]
merged
