### ISSUE TITLE
Backporting to earlier versions of QuickCheck

### ISSUE THREAD

**Issue by skeuchel** [andrewthad/quickcheck-classes#50]
I would like to build against distribution provided packages such as

Debian Stretch 9.5 (QuickCheck-2.8.2, GHC-8.0.1) and
Ubuntu 16.04.5 LTS (QuickCheck-2.8.1, GHC-7.10.3)

which are however outside of the current supported range and I would like to see them supported since these are currently supported distributions. Are you interested as well? I can do the backporting myself, but I would only bother if you're also interested in merging.

I don't specifically care about these but maybe they are low hanging fruit:

Debian Jessie 8.11 (QuickCheck-2.7.6, GHC-7.6.3)
Stackage LTS Haskell 2.22 (QuickCheck-2.7.6, GHC-7.8.4)
Ubuntu 14.04.5 LTS (QuickCheck-2.6, GHC-7.6.3)

**Comment by andrewthad** [comment]
I would certainly take a PR that added support for older versions of QuickCheck.
