### ISSUE TITLE
Alternatives to Eq1 and Show1

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/quickcheck-classes#52]
Gabriel Labec writes:

> I am looking at using `quickcheck-classes` over `checkers` b/c the former properly checks the actual traversable laws. However, I'm not sure if I'm missing something or not. The lib's readme states: "This library differs from other solutions by not introducing any new typeclasses that the user needs to learn." Yet when I attempt to use `traversableLaws`, I need instances of Eq1, Show1, and Arbitrary1 defined for my own types. These classes are new to me (not surprising, everything in Haskell is somewhat new to me). They don't seem extremely complex, but neither do they seem extremely trivial.

> Is there a typical pattern / helper function / easy boilerplate way to define these instances for my own data types? By comparison, checkers' `eqProp` function seems easier, not harder. That seems to contradict this library's stated purpose. But it is also very likely I am missing something.

> Thanks for any insight you may be able to shine on the matter. I appreciate it.

In the libraries readme, the claim that it doesn't "introduce any new typeclasses" would be more accurately phrased as "define any new typeclasses". `Eq1` and friends are in `base`, so this library merely uses existing typeclasses.

Nevertheless, the pain described is real. GHC lacks any native support for generating `Eq1` instances. Ryan Scott has conjured up some [template haskell that can write the instances for you](http://hackage.haskell.org/package/deriving-compat-0.5.2/docs/Data-Eq-Deriving.html), but people working on simple libraries often don't like to take a `template-haskell` dependency. To entirely eliminate the use of `Eq1`, we could go the route of `checkers` and use `FlexibleContexts`. But I loath `FlexibleContexts` because, in this setting, it causes type signatures to leak information about the implementation. Consider the `checkers` definition of `functor`:

    functor :: forall m a b c. (Functor m, Arbitrary a, Arbitrary b, Arbitrary c, CoArbitrary a, CoArbitrary b, Show (m a), Arbitrary (m a), EqProp (m a), EqProp (m c)) => m (a, b, c) -> TestBatch

Why is the caller of the function responsible for picking out `a`, `b`, and `c`? A `Functor` should be polymorphic over its type. The implementation, not the end user, should be responsible for choosing whatever the type constructor `m` is applied to. And this is exactly what `quickcheck-classes` is able to offer:

    functorLaws :: (Functor f, Eq1 f, Show1 f, Arbitrary1 f) => proxy f -> Laws

So, for somewhat dogmatic reasons, I dislike the solution that `checkers` offers because the type signature it gives the function is inappropriate. But, one may rightfully complain that my dogma is getting in the way of real conveniences. And yes, that has historically been the case, but several days ago, a new hope arrived. With the [release of GHC 8.6.1](https://ghc.haskell.org/trac/ghc/blog/ghc-8.6.1-released), we now have access to the `QuantifiedConstraints` extension. Had this existed ten years ago, `Eq1` would have never been invented. We can now write:

    functorLaws :: (Functor f, (forall a. Eq a => Eq (f a)), (forall a. Show a => Show (f a)), (forall a. Arbitrary a => Arbitrary (f a)) => proxy f -> Laws

This type signature captures the convenience afforded by `checkers` and the precision afforded by `quickcheck-classes`. And this is what I plan on switching to. The plan is to put a bunch of CPP in the library so that when compiling with GHC 8.6 and above, it uses `QuantifiedConstraints`. Otherwise, it will fall back to `Eq1`, `Show1`, and `Arbitrary1`. I'm planning on implementing this in the next week.

**Comment by glebec** [comment]
Thanks for the response!

**Comment by chessai** [comment]
@glebec please feel free to open an issue in the future! This one was most welcome.
