### ISSUE TITLE
Generic(1) laws

### ISSUE THREAD

**Issue by RyanGlScott** [andrewthad/quickcheck-classes#57]
I found myself recently searching through `quickcheck-classes` to find something which would test the `Generic` and `Generic1` laws:

```haskell
-- from . to ≡ id
-- to . from ≡ id
--
-- from1 . to1 ≡ id
-- to1 . from1 ≡ id
```

But I couldn't find anything. Do you think these would be difficult to add? The one thing that makes me nervous is that some of these laws require expressing constraints in terms of the `Rep(1)` type family, and [type families tend not to mix well with quantified constraints](https://ghc.haskell.org/trac/ghc/ticket/14860).

**Comment by RyanGlScott** [comment]
> Out of curiosity, are these instances you are wanting to check hand-written, or are you trying to validate instances generated by GHC?

A little bit of both, actually—they're generated through the `generic-deriving` library's Template Haskell machinery, so I'd like to verify that the generated code actually does what I'd expect it to.

**Comment by chessai** [comment]
I have something, just having to build it against GHC 7.4 to 8.6 now.

**Comment by chessai** [comment]
please see PR #58
