### ISSUE TITLE
Support for older aeson

### ISSUE THREAD

**Issue by skeuchel** [andrewthad/quickcheck-classes#69]
I would like to build the library against aeson 0.11.2.1 which shipped with Debian Stretch and would propose to loosen the lower bound. @andrewthad You recently introduced 1.1 as a lower bound here https://github.com/andrewthad/quickcheck-classes/commit/ade4948ef778488074763e9376b27dec3d5bbe97#diff-6929919410ee2e82c3f53d55f537e093R93 . Did you have any specific reason to choose 1.1?

**Comment by andrewthad** [comment]
There was no particular reason. It's possible that this library builds fine with `aeson-0.11`. I just haven't tried.

**Comment by chessai** [comment]
I am fine with this as well. If you want to put a PR up.
