### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by Bodigrim** [andrewthad/quickcheck-classes#95]
Do you have any plans to make `quickcheck-classes` available from Stackage? Currently if I use `quickcheck-classes` in tests, I basically cannot upload my package on Stackage as well. 

Sure, one can disable running tests on Stackage, etc., but this is not very convenient.

**Comment by andrewthad** [comment]
I think having this on stackage  is reasonable.  I can do this later today if no one else has done it before then.

**Comment by chessai** [comment]
@Bodigrim sorry for not getting to this quickly.
