### ISSUE TITLE
monoidLaws: Check that mappend == (<>)?

### ISSUE THREAD

**Issue by sjakobi** [andrewthad/quickcheck-classes#99]
Actually the docs for `Monoid` don't demand this explicitly but I think it makes a lot of sense.

**Comment by chessai** [comment]
I've thought about this before and I'm inclined to agree.

**Comment by andrewthad** [comment]
I agree that it should always be the case that mapped and <> have the same behavior. A PR for this would be most welcome.

**Comment by sjakobi** [comment]
> A PR for this would be most welcome.

I'm on it! :)

**Comment by chessai** [comment]
just did this

**Comment by sjakobi** [comment]
@chessai Wouldn't it be better to include the new property in `monoidLaws` since `Semigroup` is a superclass of `Monoid`?

**Comment by chessai** [comment]
@sjakobi i don't think so, because our support window is so large (back to GHC 7.4)

i'm quite tired so maybe just not thinking clearly

**Comment by sjakobi** [comment]
I suspect that most users use recent version of GHC but I might be wrong.

`checkers` simply keeps the property behind some CPP: https://github.com/conal/checkers/blob/0931e2f142a0f0756a5e0e4593ba4a53cea127aa/src/Test/QuickCheck/Classes.hs#L135-L137

**Comment by chessai** [comment]
You're right that most users use recent versions, but some don't, and I try to assume the worst.

I didn't want to put it behind CPP because some of these users might have monoid instances without semigroup! However it might make more sense to just do what checkers does.
